# Generated by Django 6.0 on 2025-12-30 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id_recurso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('infografia', 'Infografía'), ('video', 'Video'), ('consejo', 'Consejo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCafeteria',
            fields=[
                ('id_cafeteria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('turno_inicio', models.TimeField(blank=True, null=True)),
                ('turno_fin', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id_trivia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_admin',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Consejo',
            fields=[
                ('id_recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consejo', serialize=False, to='API.recursos')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infografia',
            fields=[
                ('id_recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='infografia', serialize=False, to='API.recursos')),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video', serialize=False, to='API.recursos')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='API.administrador')),
                ('id_cafeteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='API.personalcafeteria')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='API.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('alerta', models.BooleanField(default=False)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='API.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('permitido', models.BooleanField(default=True)),
                ('informacion_nutricional', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('sellos', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentos', to='API.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='API.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('opcion_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_correcta', models.CharField(blank=True, max_length=1, null=True)),
                ('id_trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='API.trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sugerencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id_recomendacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='API.alimento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoActividad',
            fields=[
                ('id_progreso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='API.recursos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoEncuesta',
            fields=[
                ('id_intento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('id_trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='API.trivia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_transaccion', models.DateTimeField(blank=True, null=True)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='API.alimento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='API.alimento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='API.alimento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='API.personalcafeteria')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='API.producto')),
            ],
        ),
    ]
