# Generated by Django 6.0 on 2026-01-06 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_calificacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
