# Generated by Django 6.0 on 2025-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_recursos_personalcafeteria_producto_trivia_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('FRUTAS', 'Frutas'), ('BEBIDAS', 'Bebidas'), ('LACTEOS', 'Lácteos'), ('SNACKS', 'Snacks')], max_length=50, null=True),
        ),
    ]
