# Generated by Django 6.0 on 2026-01-01 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_alimento_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intentoencuesta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progresoactividad',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to=settings.AUTH_USER_MODEL),
        ),
    ]
