# Generated by Django 6.0 on 2026-01-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_calificacion_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejo',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consejo',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consejo',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
